[package]
name = "codeowners-enforcer"
version = "0.1.0" # generated
authors = ["Jamie Kyle <me@thejameskyle.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
ignore = "0.4.7"
codeowners = "0.1.3"
ansi_term = "0.11.0"
